# Generated by Django 5.2.4 on 2025-12-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_project_id_alter_skill_id_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='giturl',
            field=models.CharField(default='', max_length=500),
        ),
    ]
